### ISSUE TITLE
Responsive FileManager

### ISSUE THREAD

**Issue by diegow88** [stfalcon/TinymceBundle#143]
Hi,

I have installed the Responsive FileManager (http://www.responsivefilemanager.com/). So far, with the documentation I've made it work. I can manage files and insert them straight from there.

Now, in the plugin's demo site (http://www.responsivefilemanager.com/demo.php) I've noticed that when you use the Image plugin to insert an image, there is a button that allows you to browse and choose an image. This fills the input with the URL.
I understand that it's required to modify the Image plugin (http://www.responsivefilemanager.com/js/tinymce/plugins/image/plugin.js) in order to be able to add this functionality but I didn't succeed so far.

Has someone done it so far? Or can someone give me a hint?
Thanks,
Diego.

**Comment by LogansUA** [comment]
@diegow88 Hello. Is this issue still actual?

**Comment by jimiero** [comment]
In case this helps someone, if you want to use Responsivefilemanager:

here is an example of  bundle config file:

config/packages/stfalcon_tinymce.yaml

`stfalcon_tinymce:
        external_plugins:
            filemanager:
                url: "asset[/tinymce/tinymce/plugins/responsivefilemanager/plugin.min.js]"
            imagemanager:
                url: "asset[/bundles/stfalcontinymce/vendor/tinymce/plugins/image/plugin.min.js]"
        include_jquery: false
        tinymce_jquery: false
        selector: ".tinymce"
        #base_url: "http://yourdomain.com/" # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
        # Get current language from the parameters.ini
        language: '%locale%'
        # Custom buttons
        tinymce_buttons:
        #    stfalcon: # Id of the first button
        #        title: "Stfalcon"
        #        image: "http://stfalcon.com/favicon.ico"
        theme:
            # Simple theme: same as default theme
            simple:
                 plugins:
                     - "responsivefilemanager advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                 filemanager_title: ['File manager']
                 external_filemanager_path: ['/tinymce/filemanager/']
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image| responsivefilemanager"
                 toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
                 image_advtab: true
                 templates:
                     - {title: 'Test template 1', content: 'Test 1'}
                     - {title: 'Test template 2', content: 'Test 2'}
            # Advanced theme with almost all enabled plugins
            advanced:
                 plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                 toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
                 image_advtab: true
                 templates:
                     - {title: 'Test template 1', content: 'Test 1'}
                     - {title: 'Test template 2', content: 'Test 2'}
            # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
            bbcode:
                 plugins: ["bbcode, code, link, preview"]
                 menubar: false
                 toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
`
