### ISSUE TITLE
Absolute URLs

### ISSUE THREAD

**Issue by JRomeoSalazar** [stfalcon/TinymceBundle#148]
Hi, I'm trying to insert images but I always get a "not found" error because TinyMCE uses relative urls. I would like to use absolute url and TinyMCE has a few properties to configure this, but I'm not able to configure them.

For example:

```
{{ tinymce_init({
        relative_urls: false,
        remove_script_host: false,
        convert_urls: true
    }) }}
```

How can I pass this parameters to TinyMCE?

**Comment by LogansUA** [comment]
@JRomeoSalazar Is this issue still relevant?

**Comment by 4string** [comment]
The setting I mentioned fixed the problem.
