### ISSUE TITLE
Plugins callbacks

### ISSUE THREAD

**Issue by charlieWasp** [stfalcon/TinymceBundle#152]
Hello, how can I set callbacks for tinymce plugins? I try to set 'paste_postprocess' callback for 'paste' plugin. If I put callback as a string to a config.yml, I get 'undefined is not a function' error.If I put function name in config, and declare this function in global scope, nothing happens at all.

**Comment by LogansUA** [comment]
@charlieWasp Hello. Bundle supports only 2 kind of plugins callback: `'paste_preprocess'`, and `'file_browser_callback'`, you could use them by pass this callbacks like this:
```
{{ tinymce_init({'paste_preprocess': 'function(pl, o) { console.log(pl, o) }'}) }}
```
