### ISSUE TITLE
Enable embed iframe

### ISSUE THREAD

**Issue by davidromani** [stfalcon/TinymceBundle#155]
How can I enable this feature? Thx.

**Comment by LogansUA** [comment]
@davidromani Hello. Is this issue still actual?

I found this some kind of [solution](http://stackoverflow.com/questions/5220754/is-there-a-way-to-be-able-to-insert-iframe-in-tinymce). Is it what you're looking for?

**Comment by davidromani** [comment]
I don't rembember very well but thanks for your time. We can close it for now.

Cheers.
