### ISSUE TITLE
Uncaught TypeError: Cannot read property 'newdocument' of undefined

### ISSUE THREAD

**Issue by piwi91** [stfalcon/TinymceBundle#156]
I get this error when initiating TinyMCE on multiple textarea's at once.

Example: 3 x textarea with class 'tinymce'

**Comment by LogansUA** [comment]
@piwi91 Is this issue still actual?

I've just tried to do this with 3-6 textarea's and all seems fine, don't see any errors. Maybe something in you're configuration?

**Comment by piwi91** [comment]
Hi @LogansUA,

I do not use this bundle anymore because I needed more complex configurations including plugins etc. so I can't check this for you.

If it isn't reproducible you can close this issue

**Comment by LogansUA** [comment]
@piwi91 Thank you
