### ISSUE TITLE
CSRF token invalid message when used with Sonata Admin

### ISSUE THREAD

**Issue by Szymon-GP** [stfalcon/TinymceBundle#159]
Hi,

I'm recently getting CSRF token is invalid message when I'm trying to attach tinymce editor to the textarea field.

Symfony: 2.4.10
Sonata AdminBundle: 2.2.11
TinymceBundle: v0.3.8

I'm just wondering if anyone else has got similar problem? It's working fine when I remove tinymce editor from that field.

Appreciate for any help.

**Comment by svatok13** [comment]
@stfalcon i think you can close this issue, because nobody else has this problem, and now it is to complicated to reproduce this on specified versions
