### ISSUE TITLE
Can not override the default configuration by passing an option in TWIG

### ISSUE THREAD

**Issue by casaulenbo** [stfalcon/TinymceBundle#163]
I have just install the lastest version, when i try the code below, it does not work at all.
It seems we can not override the default configuration by passing an option in TWIG

{{ tinymce_init({'use_callback_tinymce_init': true, 'theme': {'simple': {'menubar': false}}}) }}

Does the instruction correct?
https://github.com/stfalcon/TinymceBundle#include-in-template

Best regards

**Comment by nykopol** [comment]
I have the same issue. Looking at the code, this parameters are not event taken by the function.

**Comment by casaulenbo** [comment]
I have figured out the reason but i forgot to update the answer, sorry for that.
If you install by command [composer require symfony/stfalcon/tinymce-bundle] the source code is out of date. 
Handle this issues is quiet simple: just download the source code from [https://github.com/stfalcon/TinymceBundle] and overwrite the "out of date source code" the problem will be gone.
Good luck!

**Comment by Ingannatore** [comment]
We are currenty working on a [forked project](https://github.com/gibilogic/tinymce-bundle), if you're interested :)
