### ISSUE TITLE
The Twig_Function_Method class is deprecated since version 1.12

### ISSUE THREAD

**Issue by 7eey** [stfalcon/TinymceBundle#165]
Hi,

In method "getFunctions" of StfalconTinymceExtension class can you change the line 
<code>'tinymce_init' => new \Twig_Function_Method($this, 'tinymceInit', array('is_safe' => array('html')))</code>
by 
<code>new \Twig_SimpleFunction('tinymce_init', [$this, 'tinymceInit'], array('is_safe' => array('html')))</code>

Thks
Jérém

**Comment by Ingannatore** [comment]
Can you open this issue inside the [new (and maintained) project](https://github.com/gibilogic/tinymce-bundle)?

**Comment by 7eey** [comment]
it's done thanks
