### ISSUE TITLE
Is this bundle abandonned ?

### ISSUE THREAD

**Issue by tristanbes** [stfalcon/TinymceBundle#167]
Is this bundle abandonned ?
If so please name a new maintainer so the PR can be merged and new version released.

ping @stfalcon

**Comment by RubenHarms** [comment]
+1

**Comment by zanardigit** [comment]
After seeing no response from the original maintainer for a while, I forked this on https://github.com/gibilogic/tinymce-bundle. It will be published on Packagist as soon as possible. We are happy to accept your PRs. :-)

**Comment by LogansUA** [comment]
Hello everyone. No it's not abandonned, we still support it.

**Comment by tristanbes** [comment]
@LogansUA Well sorry but you can't say you support it if there's no reply in issues/pull request since a long time.
At least name one maintainer so he can help you on subjects because right now the community will use (and I use) https://packagist.org/packages/gibilogic/tinymce-bundle which already solved problems reported here since a long time ago.

**Comment by LogansUA** [comment]
@tristanbes Hello. At now I support this bundle. I already accepted (#169, #164) and closed (#163, #139) some PR's and issues.
In the meantime, I plan to do some refactoring, update TinyMCE and upgrade this bundle to 0.4.0
