### ISSUE TITLE
Upgrade for Symfony3

### ISSUE THREAD

**Issue by manuelDistefano** [stfalcon/TinymceBundle#175]
Please can you upgrade the bundle for Symfony3? 

At the moment, in StfalconTinymceExtension, you use 2 services not available in Symfony 3.0:
  
     1) "templating.helper.assets" You can use "assets.packages" instead;
     2) "request" for "request->getLocale()" method. You can use getParameter('locale')

Best regards,

Manuel

**Comment by LogansUA** [comment]
@manuelDistefano Hello. Yes, I'll do it in few days. :smile:

**Comment by manuelDistefano** [comment]
Hi,

thank you very much

**Comment by LogansUA** [comment]
@manuelDistefano or, maybe you have inspiration to do this fix?

**Comment by manuelDistefano** [comment]
Yeah,

the only class you need to change is     
Stfalcon\Bundle\TinymceBundle\Twig\Extension\StfalconTinymceExtension

You need to use "assets.packages" service instead of "templating.helper.assets" for getUrl(). Reference: https://raw.githubusercontent.com/symfony/symfony/master/UPGRADE-3.0.md

Plus, "request" service for getLocale isn't available anymore. You can container->getParameter('locale')

So, you need to change line:
     93) $assets = $this->getService('assets.packages');
     205) $assets = $this->getService('assets.packages');
     126) $config['language'] = $this->getParameter('locale');

I'm testing it with default configuration and it work.

**Comment by LogansUA** [comment]
@manuelDistefano `$this->getParameter('locale');` return locale from config.yml, but not from request.

Maybe better way to initialize new `$request` variable in `__construct` with `$container->get('request');` and use it like that `$config['language'] = $this->request->getParameter('locale');`

**Comment by manuelDistefano** [comment]
@LogansUA My mistake. You cant use `$container->get('request')` because this service dont exist anymore. You need to user 'request_stak'  `$this->container->get('request_stack')->getCurrentRequest()->getLocale()`

Sorry for bad english :)

**Comment by LogansUA** [comment]
Closing. Fixed by #176
