### ISSUE TITLE
You have requested a non-existent service "assets.packages"

### ISSUE THREAD

**Issue by bmeynell** [stfalcon/TinymceBundle#177]
Appears to have been caused by this change ~21hours ago --> https://github.com/stfalcon/TinymceBundle/commit/5f8ed022dd6a606c8f0b4da97f524b9864cd0e29#diff-f8432c8532dcc65af32e80b620cc9e61R97

Our corresponding composer.json entry:

`"stfalcon/tinymce-bundle": "0.3.*@dev",`

dev-master only requires >= symfony 2.1. We're running 2.3.35. Does this bundle still work with Symfony 2.3?

How do we fix this error?

**Comment by LogansUA** [comment]
@bmeynell Hello. Thank you.

Try to use the `0.3.9` version. (`composer require stfalcon/tinymce-bundle:0.3.9`)

**Comment by thomas-fenoul** [comment]
Hi,

Same issue on 2.6.10, thx @LogansUA for the solution !

**Comment by bmeynell** [comment]
Hi @LogansUA. Thanks for the tip. Works!

However, minor, but I'm now getting a JS Console warning:

```
'webkitMovementX' is deprecated. Please use 'movementX' instead.
'webkitMovementX' is deprecated. Please use 'movementX' instead.
```

**Comment by LogansUA** [comment]
@bmeynell Hello agan :smile: 

Are you sure that this warnings because of TinyMCE? Do you use some external plugins?

**Comment by elhef** [comment]
Hello all,
Same problem on Symfony 2.3.36, thanks for the tip too :)
We have those JS warnings too, same if we disable all plugins.

**Comment by Geolim4** [comment]
@LogansUA  Thanks for the fix

**Comment by cassianotartari** [comment]
+1 still happening the error

fixed going back to ``0.3.9``

**Comment by cassianotartari** [comment]
Going under code find the reason of the issue:

In the file extension: ``StfalconTinymceExtension``

Replace this:
```php
$assets = $this->getService('assets.packages');
```

For this:
```php
$assets = $this->getService('templating.helper.assets');
```

**Comment by LogansUA** [comment]
Finally we have release versions :smile: 

Use `~1.0` for `symfony >= 2.1 and <= 2.8` or `~2.0` for `symfony >= 3.0`

Tags under `1.0` now are not supported

**Comment by barik94** [comment]
@LogansUA what about v2.0?
SF 2.4.
I have the same error

**Comment by barik94** [comment]
if try to use versions 1.0, 1.1 - throws error
```
ContextErrorException: Warning: explode() expects parameter 2 to be string, array given in /Users/lazyants/projects/academy-mlm/vendor/stfalcon/tinymce-bundle/Stfalcon/Bundle/TinymceBundle/Twig/Extension/StfalconTinymceExtension.php line 154
```

**Comment by LogansUA** [comment]
@barik94 Hi, this problem refers to #205 issue. I'm not maintain this bundle anymore. If you want, create PR and i'll merge it.

**Comment by barik94** [comment]
@LogansUA #206

**Comment by barik94** [comment]
@LogansUA could you make release? or how can I get this last commit update for my project?

**Comment by LogansUA** [comment]
@barik94 Try to use "dev-master" in composer.json

**Comment by barik94** [comment]
@LogansUA really? 
stfalcon/tinymce-bundle dev-master requires symfony/symfony >=3.0
now we use 2.4. It's unbelievable update all vendors for compatibility

**Comment by LogansUA** [comment]
@barik94 Oh, sorry. Okay, can you make the same PR as #206 to 1.x branch and i'll make new release.

**Comment by barik94** [comment]
@LogansUA #208

**Comment by LogansUA** [comment]
@barik94 Should work now, update to v1.1.1
