### ISSUE TITLE
Apply to textarea without id

### ISSUE THREAD

**Issue by charlieWasp** [stfalcon/TinymceBundle#179]
Hi there,

Just found out this line in `init.standard.js` file:

```
if (textareas[i].getAttribute('id') === '') {
     textareas[i].setAttribute("id", "tinymce_" + Math.random().toString(36).substr(2));
 }
```

If `id` attribute is not set, `getAttribute` returns `null`, so this condition will be falsy. And tinymce won't be applied, because it relies on `id`.

Am I missing something?

**Comment by LogansUA** [comment]
@charlieWasp  Hello.

Yup you right. Fixing this. Thanks.

**Comment by LogansUA** [comment]
Done for #182 `v3.9`
Done for #181 `v4.*`
