### ISSUE TITLE
missing imagetools plugin

### ISSUE THREAD

**Issue by treetop1500** [stfalcon/TinymceBundle#180]
The imagetools plugin doesn't appear to come packaged with your bundle.  I downloaded a fresh copy of the plugin 4.3.2, and tried to load it as an external bundle and that did not work either.  Is there not support for this plugin with the bundle at this time?

**Comment by mitrae** [comment]
confirm

**Comment by devozanges** [comment]
I hope you will work for it, because that's the reason why I use this bundle... ^^

**Comment by treetop1500** [comment]
Closing this due to no response in over 2 years. Moved on to Froala editor anyway.
