### ISSUE TITLE
Disable relative path

### ISSUE THREAD

**Issue by Eldhelion** [stfalcon/TinymceBundle#183]
So, on tinymce, I could use:

- relative_urls: false,
- convert_urls: false,

to force tinymce use full path for images, I put these on config.yml but keep getting relative path.

I`m using tinymce to create a newsletter that will be sent via email, so I need full path for the images

here is my config

```
stfalcon_tinymce:
  include_jquery: false
  tinymce_jquery: false
  selector: ".tinymce"
  language: "pt_BR"
  theme:
    simple:
      theme: "modern"
      plugins: [ "anchor link image table  code fullscreen preview textcolor lists" ]
      toolbar: ["undo redo | bold italic | forecolor backcolor | table | link image | alignleft aligncenter alignright | code | fullscreen | preview"]
      statusbar:  false,
      menubar:    false,
      relative_urls: false,
      convert_urls: false,
      width: "349px"
```
I don't know if my fault or a bug, I didn't saw anything on the documentation of this bundle

**Comment by LogansUA** [comment]
@Eldhelion Hi. Thanks for issue. I'll check it.

**Comment by LogansUA** [comment]
@Eldhelion did you see this issue #44?

**Comment by Eldhelion** [comment]
@LogansUA 
I had not saw it before, gave a look at it now.
I have to say that before creating this issue I had put document_base_url, but outside the theme scope
```
stfalcon_tinymce:
    document_base_url: <url>
```

and it not worked, but after some time working on other things I realised that I had copy/paste my config from pure tinymce, and so my config.yml still had "," at the end of each parameter, as you can see on my first post on 

      statusbar:  false**,**
      menubar:    false**,**
      relative_urls: false**,**
      convert_urls: false**,**


Fixed it, and man, it works o/, 
thank you very much for the quick response, and sorry for the trouble

**Comment by LogansUA** [comment]
@Eldhelion oh, yeah now i see :smile: 

No problem. Good luck.
