### ISSUE TITLE
non-existent service "request_stack"

### ISSUE THREAD

**Issue by chriscadcw** [stfalcon/TinymceBundle#192]
I am currently working with a Symfony 2.3 site and had run into the same issue that was listed in #177.  After following the last comment in the thread and updating the version number to "~1.0" I instead get an error that states:

`"You have requested a non-existent service "request_stack"`

I will admit that I do not do much with plugin development, so I'm not sure where to even look to try to fix this issue.  The line that is throwing the error is the `{{ tinymce_init() }}` in my template file.

Any help determining the best course of action to correct the issue would be greatly appreciated.  If you need any specific information about my setup, please let me know and I will do my best to provide it.

**Comment by LogansUA** [comment]
@chriscadcw Hey.

The problem is in `StfalconTinymceExtension.php` file on 130 row.
It should be not `request_stack` but `request`. I'll try to fix this soon, or you can create PR into 1.x branch and i'll check it.

**Comment by LogansUA** [comment]
Fix in #193 PR
