### ISSUE TITLE
Existing file

### ISSUE THREAD

**Issue by lena773** [stfalcon/TinymceBundle#202]
Hello, is it possible to work with the existing file? and how can i put  this file in the textarea? I have a template in docx and want to work(edit)  with this document online. Is it possible to make this with TinymceBundle?
yours respectfully,
Lena

**Comment by LogansUA** [comment]
@lena773 Hi.

Well, i'm not sure that TinyMCE can do such things, but you can resave existing *.docx file to HTML markup and then paste it into TinyMCE editor like source code. I think it should work.
