### ISSUE TITLE
Проверка типа 

### ISSUE THREAD

**Issue by novuscom** [stfalcon/TinymceBundle#205]
Если при инициализации в content указать массив - будет ошибка "An exception has been thrown during the rendering of a template ("Warning: explode() expects parameter 2 to be string, array given")"

Warning: explode() expects parameter 2 to be string, array given 
in vendor/stfalcon/tinymce-bundle/Stfalcon/Bundle/TinymceBundle/Twig/Extension/StfalconTinymceExtension.php at line 154

```
{{ tinymce_init({'theme': {
        'simple': {
            content_css: [
            '/templates/'~site.code~'/css/template_styles.css',
            '/admin/dist/css/tinymce.css'
            ],
            body_class: 'tinymce_body'
        }
    }}) }}
```

Добавьте, пожалуйста, пожалуйста небольшое условие перед 154 строкой

```php
$cssFiles = $themeOptions['content_css'];
if (!is_array($themeOptions['content_css']))
// 154 строка вот здесь 
```

т.е. не преобразовываем строку в массив, если это уже массив.

**Comment by LogansUA** [comment]
Fixed by #206
