### ISSUE TITLE
adding image uploader

### ISSUE THREAD

**Issue by ben29** [stfalcon/TinymceBundle#212]
i ddidn't find how to add image uploader
how can i all this?

**Comment by samirashirzadeh** [comment]
Hi
I have this problem to .
Please someone help me??

**Comment by nicolallias** [comment]
On TinyMCE, the official way to go is MoxieManager, [it is available for premium](https://www.tinymce.com/docs/plugins/moxiemanager/)...
I am working on two alternatives

- https://github.com/xvs32x/tinymce-responsivefilemanager -> seems not compatible with symfony
- http://www.responsivefilemanager.com -> struggling to get the parameters right
