### ISSUE TITLE
Rename `jquery.tinymce.min.js`

### ISSUE THREAD

**Issue by pribilinskiy** [stfalcon/TinymceBundle#220]
At `Resources\public\vendor\tinymce\` there are `jquery.tinymce.min.js` and `tinymce.jquery.min.js`.

@fluxuator Are you serious?

![image](https://user-images.githubusercontent.com/3078595/30536046-0bd0fc20-9c6d-11e7-86e2-f96d69fccd65.png)

**Comment by fluxuator** [comment]
@pribilinskiy this directory was copied from https://github.com/tinymce/tinymce-dist.
So, please ask the same question the authors of TinyMCE. And yes, I'm serious.

**Comment by pribilinskiy** [comment]
Ah, so it was some of the ephox devs )
