### ISSUE TITLE
Tag 2.2 release

### ISSUE THREAD

**Issue by Nyholm** [stfalcon/TinymceBundle#224]
We are really exited to make a recipe for this bundle over at https://github.com/symfony/recipes-contrib/pull/26 but we need a release that do not depend on symfony/symfony. 

What is the plan for tagging 2.2?

**Comment by Nyholm** [comment]
Ping @LogansUA

**Comment by LogansUA** [comment]
Ping @stfalcon @fre5h

**Comment by fre5h** [comment]
@Nyholm tag `v2.2.0` is ready

**Comment by Nyholm** [comment]
Awesome. Thanks
