### ISSUE TITLE
Regression in standard initialization script in 2.2.0

### ISSUE THREAD

**Issue by VincentChalnot** [stfalcon/TinymceBundle#227]
Hello,
The incriminated line:
https://github.com/stfalcon/TinymceBundle/blob/v2.2.0/Resources/public/js/init.standard.js#L21
Should be:
https://github.com/stfalcon/TinymceBundle/blob/v2.1/Resources/public/js/init.standard.js#L21
Because getElementsByClassName does'nt work with a leading "."

**Comment by nicolallias** [comment]
I ran into it too. How can those using v2.3 are not concerned?

Maybe a majority of integrators happen to pass the id instead?

**Comment by naitsirch** [comment]
This issue is fixed, now. @fre5h
