### ISSUE TITLE
relative_urls : false

### ISSUE THREAD

**Issue by david42** [stfalcon/TinymceBundle#44]
Hi,

I'd like work with the absolute URL.
In the config.yml I added this option :

relative_urls : false

see : http://www.tinymce.com/wiki.php/Configuration:relative_urls

But the URL are still relative.

How to force the absolute URL?

Thanks

**Comment by sbastias** [comment]
YES, this worked!!!! PLEASE ADD THIS TO DOCUMENTATION!!!!!

I was panicked for about an hour
