### ISSUE TITLE
Dynamically init tinyMCE on textarea elements

### ISSUE THREAD

**Issue by cve** [stfalcon/TinymceBundle#89]
How to initialize tinymce for dynamically textarea? The code from doc example:

```
tinyMCE.execCommand('mceAddControl', true, 'my_textarea_id');
```

doesn't work...
The {{ tinymce_init() }} produces the code in which there is:

```
function initTinyMCE(options) {
```

The above function is executed once when I want to use my tinyMCE.execCommand from above, it should work I think, but it's not.

**Comment by clavat** [comment]
@jhkchan If we have many TinyMCE on a page already initialized, command `initTinyMCE()` init again all of them.
So it's performance issue for client.

Maybe add the css selector into `initTinyMCE()` and load with same config all new textarea added dynamically is the answer ?
